"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Metadata = exports.InferenceResult = exports.InferenceData = exports.BBox = void 0;
var bbox_1 = require("./aitrios/bbox");
Object.defineProperty(exports, "BBox", { enumerable: true, get: function () { return bbox_1.BBox; } });
var inference_data_1 = require("./aitrios/inference-data");
Object.defineProperty(exports, "InferenceData", { enumerable: true, get: function () { return inference_data_1.InferenceData; } });
var inference_result_1 = require("./aitrios/inference-result");
Object.defineProperty(exports, "InferenceResult", { enumerable: true, get: function () { return inference_result_1.InferenceResult; } });
var metadata_1 = require("./aitrios/metadata");
Object.defineProperty(exports, "Metadata", { enumerable: true, get: function () { return metadata_1.Metadata; } });
